[project]
name = "oura-mcp-server"
version = "0.1.0"
description = "MCP server for Oura Ring data"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.15.0",
    "python-dotenv>=1.1.1",
]

